# CHAPTER 5
# Data Cleaning and Preparation

During the course of doing data analysis and modeling, a significant amount of time is spent on data preparation: loading, cleaning, transforming, and rearranging. Such tasks are often reported to take up 80% or more of an analyst’s time. Sometimes the way that data is stored in files or databases is not in the right format for a particular task. Many researchers choose to do ad hoc processing of data from one form to another using a general-purpose programming language, like Python, Perl, R, or Java, or Unix text-processing tools like sed or awk. Fortunately, pandas, along with the built-in Python language features, provides you with a high-level, flexible, and fast set of tools to enable you to manipulate data into the right form.

## 5.1 Handling Missing Data

Missing data occurs commonly in many data analysis applications. One of the goals of pandas is to make working with missing data as painless as possible. For example, all of the descriptive statistics on pandas objects exclude missing data by default. 

The way that missing data is represented in pandas objects is somewhat imperfect, but it is functional for a lot of users. For numeric data, pandas uses the floating-point value **NaN** (Not a Number) to represent missing data. We call this a *sentinel value* that can be easily detected:

In [1]:
import pandas as pd
import numpy as np

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [3]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In pandas, we’ve adopted a convention used in the R programming language by referring to missing data as **NA**, which stands for *not available*. In statistics applications, NA data may either be data that does not exist or that exists but was not observed (through problems with data collection, for example). When cleaning up data for analysis, it is often important to do analysis on the missing data itself to identify data collection problems or potential biases in the data caused by missing data. 

The built-in Python None value is also treated as NA in object arrays:

In [8]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

There is work ongoing in the pandas project to improve the internal details of how missing data is handled, but the user API functions, like pandas.isnull, abstract away many of the annoying details. See Table 5-1 for a list of some functions related to missing data handling.

<br>
<center>Table 5.1: NA handling methods</center>
<img src="Table5.1.jpg">

### 5.1.1 Filtering Out Missing Data 

There are a few ways to filter out missing data. While you always have the option to do it by hand using pandas.isnull and boolean indexing, the **dropna** can be helpful. On a Series, it returns the Series with only the non-null data and index values:

In [12]:
from numpy import nan as NA

data = pd.Series([1, NA, 3.5, NA, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [13]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

This is equivalent to:

In [15]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

With DataFrame objects, things are a bit more complex. You may want to drop rows or columns that are all NA or only those containing any NAs. **dropna** by default drops any row containing a missing value:

In [18]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],[NA, NA, NA], [NA, 6.5, 3.]])
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [22]:
cleaned = data.dropna()
cleaned

     0    1    2
0  1.0  6.5  3.0

Passing **how='all'** will only drop rows that are all NA:

In [24]:
data.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

To drop columns in the same way, pass **axis=1**:

In [22]:
data[4] = NA
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [24]:
data.dropna(axis=1, how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

A related way to filter out DataFrame rows tends to concern time series data. Suppose you want to keep only rows containing a certain number of observations. You can indicate this with the **thresh** argument:

In [37]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

          0         1         2
0  1.889273       NaN       NaN
1  0.688482       NaN       NaN
2 -0.479778       NaN -0.508991
3 -0.736933       NaN -1.481349
4 -0.390683 -0.581669 -1.689342
5  1.368968 -0.887056  2.178001
6 -0.403584 -0.380691  0.008010

In [39]:
df.dropna()

          0         1         2
4 -0.390683 -0.581669 -1.689342
5  1.368968 -0.887056  2.178001
6 -0.403584 -0.380691  0.008010

In [41]:
df.dropna(thresh=2)
# it will drop any rows that contain less than 2 observation values

          0         1         2
2 -0.479778       NaN -0.508991
3 -0.736933       NaN -1.481349
4 -0.390683 -0.581669 -1.689342
5  1.368968 -0.887056  2.178001
6 -0.403584 -0.380691  0.008010

In [33]:
data=np.array([[1,1],[1,0],[2,1],[2,1],[1,0],[NA,NA],[NA,NA]])
day=pd.DataFrame(data,index=['Mon','Tue','Wed','Thur','Fri','Sat','Sun'],columns=['PM','AM'])
day

       PM   AM
Mon   1.0  1.0
Tue   1.0  0.0
Wed   2.0  1.0
Thur  2.0  1.0
Fri   1.0  0.0
Sat   NaN  NaN
Sun   NaN  NaN

### 5.1.2 Filling In Missing Data 

Rather than filtering out missing data (and potentially discarding other data along with it), you may want to fill in the “holes” in any number of ways. For most purposes, the **fillna** method is the workhorse function to use. Calling **fillna** with a constant replaces missing values with that value:

In [43]:
df.fillna(0)

          0         1         2
0  1.889273  0.000000  0.000000
1  0.688482  0.000000  0.000000
2 -0.479778  0.000000 -0.508991
3 -0.736933  0.000000 -1.481349
4 -0.390683 -0.581669 -1.689342
5  1.368968 -0.887056  2.178001
6 -0.403584 -0.380691  0.008010

Calling **fillna** with a dict, you can use a different fill value for each column:

In [45]:
df

          0         1         2
0  1.889273       NaN       NaN
1  0.688482       NaN       NaN
2 -0.479778       NaN -0.508991
3 -0.736933       NaN -1.481349
4 -0.390683 -0.581669 -1.689342
5  1.368968 -0.887056  2.178001
6 -0.403584 -0.380691  0.008010

In [47]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0  1.889273  0.500000  0.000000
1  0.688482  0.500000  0.000000
2 -0.479778  0.500000 -0.508991
3 -0.736933  0.500000 -1.481349
4 -0.390683 -0.581669 -1.689342
5  1.368968 -0.887056  2.178001
6 -0.403584 -0.380691  0.008010

**fillna** returns a new object, but you can modify the existing object *in-place*:

In [53]:
df.fillna(0, inplace=True)
df

          0         1         2
0  1.889273  0.000000  0.000000
1  0.688482  0.000000  0.000000
2 -0.479778  0.000000 -0.508991
3 -0.736933  0.000000 -1.481349
4 -0.390683 -0.581669 -1.689342
5  1.368968 -0.887056  2.178001
6 -0.403584 -0.380691  0.008010

The same interpolation methods available for reindexing can be used with **fillna**:

In [55]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

          0         1         2
0  0.079270  0.498906  0.853648
1  1.092297  0.665003 -2.313947
2 -0.950718       NaN  0.505349
3 -0.248174       NaN  0.452979
4 -0.851985       NaN       NaN
5 -0.697600       NaN       NaN

In [57]:
df.fillna(method='ffill')

C:\Users\jingy\AppData\Local\Temp\ipykernel_59080\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

          0         1         2
0  0.079270  0.498906  0.853648
1  1.092297  0.665003 -2.313947
2 -0.950718  0.665003  0.505349
3 -0.248174  0.665003  0.452979
4 -0.851985  0.665003  0.452979
5 -0.697600  0.665003  0.452979

In [59]:
 df.fillna(method='ffill', limit=2)

C:\Users\jingy\AppData\Local\Temp\ipykernel_59080\531624609.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=2)

          0         1         2
0  0.079270  0.498906  0.853648
1  1.092297  0.665003 -2.313947
2 -0.950718  0.665003  0.505349
3 -0.248174  0.665003  0.452979
4 -0.851985       NaN  0.452979
5 -0.697600       NaN  0.452979

With **fillna** you can do lots of other things with a little creativity. For example, you might pass the *mean* or *median* value of a Series:

In [65]:
data = pd.Series([1., NA, 3.5, NA, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [67]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [89]:
import pandas as pd
import numpy as np

# Define the data with np.nan for missing values
data = [
    ['Electronics', 1280., 'Laptop', 10.],
    ['Electronics', 300., 'Tablet', 15.],
    ['Electronics', 800., 'SmartPhone', 20.],
    ['Electronics', 250., 'SmartWatch', np.nan],
    ['None', np.nan, 'HeadPhone', 25.]
]

# Create the DataFrame
product = pd.DataFrame(data, index=[0, 1, 2, 3, 4], columns=['Category', 'Price', 'Product Name', 'Stack'])
print(product)

      Category   Price Product Name  Stack
0  Electronics  1280.0       Laptop   10.0
1  Electronics   300.0       Tablet   15.0
2  Electronics   800.0   SmartPhone   20.0
3  Electronics   250.0   SmartWatch    NaN
4         None     NaN    HeadPhone   25.0

In [91]:
product['Category']=product['Category'].replace('None','Miscellauneous')
product

         Category   Price Product Name  Stack
0     Electronics  1280.0       Laptop   10.0
1     Electronics   300.0       Tablet   15.0
2     Electronics   800.0   SmartPhone   20.0
3     Electronics   250.0   SmartWatch    NaN
4  Miscellauneous     NaN    HeadPhone   25.0

In [93]:
product['Price']=product['Price'].replace(NA,60.)
product

         Category   Price Product Name  Stack
0     Electronics  1280.0       Laptop   10.0
1     Electronics   300.0       Tablet   15.0
2     Electronics   800.0   SmartPhone   20.0
3     Electronics   250.0   SmartWatch    NaN
4  Miscellauneous    60.0    HeadPhone   25.0

See Table 5-2 for a reference on **fillna**.

<br>
<center>Table 5.2:  fillna function arguments </center>
<img src="Table5.2.jpg">

https://chrisalbon.com/python/data_wrangling/pandas_missing_data/

## 5.2 Data Transformation 

So far in this chapter we’ve been concerned with rearranging data. Filtering, cleaning, and other transformations are another class of important operations. 

### 5.2.1 Removing Duplicates 

Duplicate rows may be found in a DataFrame for any number of reasons. Here is an example:

In [26]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

## The DataFrame method **duplicated** returns a boolean Series indicating whether each row is a duplicate (has been observed in a previous row) or not:

In [29]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

Relatedly, **drop_duplicates** returns a DataFrame where the duplicated array is False:

In [32]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

Both of these methods by default consider all of the columns; alternatively, you can specify any subset of them to detect duplicates. Suppose we had an additional column of values and wanted to filter duplicates only based on the 'k1' column:

In [99]:
data['v1'] = range(7)
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [101]:
data.drop_duplicates(['k1'])

    k1  k2  v1
0  one   1   0
1  two   1   1

**duplicated** and **drop_duplicates** by default keep the first observed value combination. Passing *keep='last'* will return the last one:

In [104]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [108]:
data.drop_duplicates(['k1', 'k2'], keep='last')

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### 5.2.2 Transforming Data Using a Function or Mapping 

For many datasets, you may wish to perform some transformation based on the values in an array, Series, or column in a DataFrame. Consider the following hypothetical data collected about various kinds of vegetables:

In [36]:
data = pd.DataFrame({'vege': ['cabbage', 'carrot', 'cabbage','Lettuce', 'potato', 'Cabbage', 
                             'lettuce', 'tomato', 'cucumber'],  'weight': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

       vege  weight
0   cabbage     4.0
1    carrot     3.0
2   cabbage    12.0
3   Lettuce     6.0
4    potato     7.5
5   Cabbage     8.0
6   lettuce     3.0
7    tomato     5.0
8  cucumber     6.0

Suppose you wanted to add a column indicating the seller that each food came from. Let’s write down a mapping of each distinct vegetables type to the seller:

In [39]:
vege_to_seller = {'cabbage': 'David',  'carrot': 'David',  'lettuce': 'Ahmad',  'potato': 'Ahmad', 
                  'tomato': 'David',  'cucumber': 'Tina'}

The **map** method on a Series accepts a function or dict-like object containing a mapping, but here we have a small problem in that some of the vegetables are capitalized and others are not. Thus, we need to convert each value to lowercase using the **str.lower** Series method:

In [42]:
lowercased = data['vege'].str.lower()
lowercased

0     cabbage
1      carrot
2     cabbage
3     lettuce
4      potato
5     cabbage
6     lettuce
7      tomato
8    cucumber
Name: vege, dtype: object

In [44]:
data['seller'] = lowercased.map(vege_to_seller)
data

       vege  weight seller
0   cabbage     4.0  David
1    carrot     3.0  David
2   cabbage    12.0  David
3   Lettuce     6.0  Ahmad
4    potato     7.5  Ahmad
5   Cabbage     8.0  David
6   lettuce     3.0  Ahmad
7    tomato     5.0  David
8  cucumber     6.0   Tina

We could also have passed a function that does all the work:

In [47]:
data['vege'].map(lambda x: vege_to_seller[x.lower()])

0    David
1    David
2    David
3    Ahmad
4    Ahmad
5    David
6    Ahmad
7    David
8     Tina
Name: vege, dtype: object

Using **map** is a convenient way to perform element-wise transformations and other data cleaning–related operations.

### 5.2.3 Replacing Values 

Filling in missing data with the **fillna** method is a special case of more general value replacement. As you’ve already seen, **map** can be used to modify a subset of values in an object but **replace** provides a simpler and more flexible way to do so. Let’s consider this Series:

In [37]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

The -999 values might be sentinel values for missing data. To replace these with NA values that pandas understands, we can use replace, producing a new Series (unless you pass inplace=True):

In [38]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

If you want to replace multiple values at once, you instead pass a list and then the substitute value:

In [39]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

To use a different replacement for each value, pass a list of substitutes:

In [40]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

The argument passed can also be a dict:

In [41]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

The **data.replace** method is distinct from **data.str.replace**, which performs string substitution element-wise. We look at these string methods on Series later in the chapter.

### 5.2.4 Renaming Axis Indexes 

Like values in a Series, axis labels can be similarly transformed by a function or mapping of some form to produce new, differently labeled objects. You can also modify the axes in-place without creating a new data structure. Here’s a simple example:

In [122]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), index=['Ohio', 'Colorado', 'New York'], 
                    columns=['one', 'two', 'three', 'four']) 
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

Like a Series, the axis indexes have a **map** method:

In [126]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

You can assign to **index**, modifying the DataFrame in-place:

In [129]:
data.index = data.index.map(transform)
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

If you want to create a transformed version of a dataset without modifying the original, a useful method is **rename**:

In [45]:
data.rename(index=str.title, columns=str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

Notably, **rename** can be used in conjunction with a dict-like object providing new values for a subset of the axis labels:

In [46]:
 data.rename(index={'OHIO': 'INDIANA'},columns={'three': 'peekaboo'})

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

**rename** saves you from the chore of copying the DataFrame manually and assigning to its **index** and **columns** attributes. Should you wish to modify a dataset in-place, pass *inplace=True*:

In [133]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

         one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### 5.2.5 Discretization and Binning 

Continuous data is often discretized or otherwise separated into “bins” for analysis. Suppose you have data about a group of people in a study, and you want to group them into discrete age buckets:

In [149]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

Let’s divide these into bins of 18 to 25, 26 to 35, 36 to 60, and finally 61 and older. To do so, you have to use **cut**, a function in pandas:

In [153]:
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

The object pandas returns is a special **Categorical** object. The output you see describes the bins computed by **pandas.cut**. You can treat it like an array of strings indicating the bin name; internally it contains a **categories** array specifying the distinct category names along with a labeling for the **ages** data in the codes attribute:

In [164]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [166]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [168]:
pd.value_counts(cats) 
#(exclude,[]include

C:\Users\jingy\AppData\Local\Temp\ipykernel_59080\258213710.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

Note that **pd.value_counts(cats)** are the bin counts for the result of **pandas.cut**. 

Consistent with mathematical notation for intervals, a parenthesis means that the side is open, while the square bracket means it is closed (inclusive). You can change which side is closed by passing right=False:

In [162]:
 pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

You can also pass your own bin names by passing a list or array to the **labels** option:

In [54]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

If you pass an integer number of bins to **cut** instead of explicit bin edges, it will compute equal-length bins based on the minimum and maximum values in the data. Consider the case of some uniformly distributed data chopped into fourths:

In [170]:
data = np.random.rand(20)
data

array([0.48268311, 0.79756628, 0.03530778, 0.30586245, 0.86448758,
       0.02099352, 0.65102535, 0.43017154, 0.16750312, 0.96981516,
       0.90081142, 0.27584912, 0.29471799, 0.23690376, 0.49963379,
       0.06599838, 0.74131673, 0.3696032 , 0.59585896, 0.56877845])

In [172]:
pd.cut(data, 4, precision=2)

[(0.26, 0.5], (0.73, 0.97], (0.02, 0.26], (0.26, 0.5], (0.73, 0.97], ..., (0.02, 0.26], (0.73, 0.97], (0.26, 0.5], (0.5, 0.73], (0.5, 0.73]]
Length: 20
Categories (4, interval[float64, right]): [(0.02, 0.26] < (0.26, 0.5] < (0.5, 0.73] < (0.73, 0.97]]

The *precision=2* option limits the decimal precision to two digits. 

A closely related function, **qcut**, bins the data based on sample quantiles. Depending on the distribution of the data, using **cut** will not usually result in each bin having the same number of data points. Since **qcut** uses sample quantiles instead, by definition you will obtain roughly equal-size bins:

In [174]:
data = np.random.randn(1000)  # Normally distributed
data

array([ 1.13913455e-01,  9.98032188e-01,  1.06371767e+00, -6.97912857e-01,
        1.32294621e+00, -1.17527409e+00, -1.89090940e+00, -2.28427274e+00,
       -3.18084986e-01,  6.02632772e-01, -6.22623602e-01,  9.01673755e-01,
       -1.49233445e+00,  7.87497757e-01, -1.73026329e+00, -6.41584857e-01,
       -9.02711416e-01, -2.00359176e-01, -1.80299855e+00, -7.59362140e-01,
        1.14433810e-01,  6.18859131e-01,  1.54718564e+00,  2.13827375e-01,
       -8.73336997e-01, -1.07586035e+00, -2.26933026e-01,  2.76967000e-01,
        7.84930596e-01,  1.00742713e+00, -5.42478626e-01, -1.30016088e+00,
        4.94485178e-01, -1.96691124e+00, -4.30627509e-01, -1.31789709e+00,
       -3.79665371e-01,  6.55760548e-01,  1.47768707e+00,  6.48198985e-01,
       -4.44167401e-01,  3.52425536e-01, -6.89405064e-01,  1.17647557e+00,
        4.08041340e-01, -7.87733951e-01, -8.63314311e-01,  5.55792217e-01,
        5.12033700e-01,  5.04300774e-01,  6.65014470e-01,  1.97440162e-01,
       -9.59703405e-01, -7.14803171e-01,  9.09385960e-01, -4.25441647e-01,
       -9.92935408e-02,  3.06226710e-01, -3.19428904e-01,  1.84471982e-01,
        8.92018487e-01, -1.23006803e+00, -6.38587723e-01, -1.48450875e+00,
        4.10251219e-01, -9.19317010e-03, -6.22200272e-01, -1.13870648e+00,
       -7.70579383e-01, -6.21217555e-01,  1.32272407e+00,  1.77894720e+00,
        2.13072860e-01, -1.32898563e-01, -4.53934050e-01,  3.15582740e-01,
       -1.30073974e-01, -1.11338519e+00, -2.44726566e-01, -3.12549179e-01,
       -1.13598561e-01, -3.77036472e-01,  1.52543157e+00,  5.55407061e-01,
        6.53466839e-01,  2.93723328e-01, -1.13200653e+00,  1.70603587e+00,
       -1.54990629e+00,  5.43008305e-01, -1.21127042e+00,  2.20826488e+00,
       -1.03639806e+00,  2.16743365e-01,  5.12942600e-01, -5.31381153e-01,
       -1.30488829e-01, -1.67066764e+00, -5.54835711e-01,  1.89168536e+00,
       -1.23811690e+00, -1.26113850e+00,  1.24936373e+00,  1.51728028e+00,
        1.23910626e-01,  4.07419447e-01,  1.25425769e+00,  1.44751844e+00,
       -1.91315118e-01, -9.89915055e-01, -2.87362882e-01,  7.55424230e-01,
       -2.72276165e-01, -1.01378301e+00,  8.15170744e-01, -1.83630171e+00,
        1.42518814e-01,  3.14781019e-01, -9.62817870e-01, -8.34506139e-01,
       -5.19102044e-01,  1.41344815e+00,  1.03022318e+00, -9.27875217e-01,
        5.02499615e-01, -7.24067389e-01, -1.09001149e+00, -1.78572837e-01,
        9.83043316e-01,  1.29248965e-01, -6.01283059e-01,  2.86312252e-01,
       -1.04602385e-01, -1.64657181e+00, -7.59377232e-01, -1.30262381e+00,
        2.84042466e-01, -1.07835653e+00, -3.48559692e-01,  5.63536452e-01,
       -5.65010753e-01,  1.13431195e+00,  2.96340264e-01,  1.07472488e+00,
        8.90360133e-01,  9.23866762e-01, -8.91025005e-01,  8.93910489e-01,
       -4.96646679e-01, -1.11229915e+00,  1.95093623e-01, -7.67537399e-01,
       -3.97198428e-01,  6.59507167e-01,  9.36658266e-01,  1.01061538e-01,
       -4.73456440e-01, -2.25022897e+00,  7.31591971e-01,  1.27967977e+00,
       -5.30213601e-01, -1.02087734e+00,  1.38769148e-01, -6.70807595e-01,
        1.09566427e-01,  4.10787980e-01, -1.22879760e-01,  3.59147435e-01,
       -1.63481358e+00,  1.73833494e+00, -8.64869007e-01,  1.38386265e+00,
        1.96973991e+00, -1.23147954e+00, -1.17967752e-01,  7.05343652e-01,
       -8.89331060e-01, -1.96643432e-01,  9.10514109e-01, -2.06456080e+00,
        2.83591034e-04, -1.81922784e-01,  1.13123216e+00,  1.92360136e-01,
        1.04176355e+00, -1.23164131e+00, -1.21010826e+00,  1.74199481e+00,
        3.15529162e-01,  4.43783114e-01, -2.73570746e+00,  4.30409906e-01,
        2.99798002e-01, -6.14703174e-01, -1.17709586e+00,  5.52648220e-01,
       -1.07044737e-02, -3.25903867e-01,  1.20083364e+00, -1.09344570e+00,
       -1.26975970e+00, -9.80654475e-01, -6.46253455e-01, -5.31648874e-01,
        5.02227198e-01, -5.52389471e-01, -4.00642446e-01,  5.96765465e-01,
       -2.28234368e-01,  6.91893907e-01,  4.02090412e-03, -1.23856745e+00,
       -9.13043813e-01,  1.26848630e+00,  1.52924770e+00, -7.72918343e-01,
       -8.62248099e-01,  1.54911241e+00,  4.27080026e-01, -7.36866585e-02,
        4.19773120e-01, -1.65733030e-01,  4.50749755e-01,  1.05850754e+00,
       -7.79405220e-01, -1.64641057e+00,  4.56407351e-01,  4.57275156e-02,
        4.60114885e-01,  2.71059667e+00,  1.05021233e+00,  1.04051366e-02,
       -9.79908263e-01, -2.08061466e+00,  2.25217964e-01, -4.41823881e-01,
       -6.23400534e-01, -8.14225398e-01,  3.65065318e-01, -3.06839003e-01,
       -3.98071929e-01,  7.98005394e-01,  5.98022913e-01, -1.87996169e-01,
       -3.17667950e-01,  3.60123495e-03, -1.47098527e-01, -6.28927607e-02,
       -1.10707257e+00,  1.09575832e-02, -7.95858691e-01,  3.19439162e-01,
       -3.17880796e-01,  1.98266478e+00, -5.04245505e-01,  6.46882548e-01,
       -5.34167019e-01, -6.53887416e-01,  9.55784798e-01,  1.09809642e+00,
        2.23615182e+00, -6.57689758e-01, -1.84913585e+00,  1.15398512e+00,
        7.95199704e-02, -3.13528143e-01,  6.00715158e-02,  2.78282414e-01,
       -6.15044518e-01, -1.81668737e+00, -4.27089812e-01, -1.36818282e-01,
       -9.60734383e-04,  1.39052292e+00, -1.88826756e+00, -1.31097386e+00,
        1.35328209e+00, -6.51406562e-01,  1.24327100e+00, -3.66145823e-01,
        1.68432824e+00,  1.44897773e+00,  1.99241025e+00,  2.06788279e+00,
       -3.70828696e-01, -9.12546820e-01, -1.85245166e-01,  3.10491557e-01,
        8.55336313e-01, -1.62048718e+00, -5.08779308e-01,  6.60319027e-01,
        1.13881124e+00, -8.22152904e-01, -9.68413507e-02,  6.17557793e-01,
        5.70161518e-01,  8.39190651e-01, -7.76771324e-01,  3.71227825e-01,
        1.51203168e-01,  2.00789294e+00,  2.52697538e-02,  1.38191231e+00,
       -1.66996521e+00, -7.78959501e-01,  1.33633398e+00,  1.93554021e+00,
        2.85876211e+00,  1.32953340e+00, -1.64835590e-01,  1.03133873e-01,
        1.03810409e+00, -2.53195634e+00, -9.26493126e-02, -1.08357964e+00,
        5.10719934e-01,  5.59881716e-01,  8.55025828e-01, -1.64283208e+00,
        1.20059186e+00,  7.33697371e-01, -1.74374486e+00,  3.24622361e-01,
       -8.46334163e-01, -3.18506224e-01,  2.37530501e-01, -8.19077979e-01,
        2.88999185e-01,  1.04264841e-01, -2.20081315e+00,  2.12351891e+00,
        1.41222183e+00, -9.89616788e-01, -1.53435749e+00,  1.12189754e+00,
        1.19278853e+00,  1.26109630e+00,  1.14413135e+00,  1.67403234e+00,
       -7.41333604e-01, -2.07332297e-01, -4.74581194e-01, -1.88122912e+00,
       -9.11205101e-01,  2.41040036e-01, -1.24584038e+00,  8.51685265e-02,
       -1.28499681e+00, -6.88324738e-01,  1.34272815e+00, -5.24958523e-01,
        7.37293265e-01,  8.77642370e-01,  3.17827568e-01, -1.81253098e-01,
       -7.55782596e-01,  6.63671428e-01,  3.74753478e-01,  4.18769503e-01,
        5.95979734e-02, -8.05804696e-01,  4.27567018e-01, -1.11204468e+00,
        2.55054457e-01,  5.24456742e-01,  2.25876925e+00,  4.07523576e-01,
        3.64205715e-01, -3.09302117e-02, -1.00816712e+00, -1.48515400e-02,
        1.29103975e+00, -1.82534161e+00, -4.49954373e-01,  5.95035689e-01,
       -2.29092148e-01, -1.10720337e+00, -2.45073127e-02, -1.50974396e-01,
       -2.18951333e-01,  6.07135447e-02, -9.27571675e-01, -1.60003950e-01,
       -1.30902672e-01,  7.95582305e-01, -9.03704254e-01, -3.40356533e-01,
        2.41851480e-01,  6.87674130e-01, -6.64384091e-01,  6.40895976e-01,
       -1.27049728e+00,  1.18330898e+00, -6.92941832e-01, -5.11524331e-01,
        1.33264670e+00,  1.42700661e+00,  3.98339044e-01,  1.17138237e+00,
        1.64440145e+00, -8.86271867e-01, -9.99187991e-01, -1.05942346e-01,
       -1.73507652e+00, -5.74215019e-01, -6.16560577e-01, -6.03894784e-02,
       -6.25042330e-01,  1.43988676e+00,  4.05571443e-01, -1.31379189e+00,
       -5.18461754e-01,  2.39838877e-01, -9.91707866e-01, -2.09764896e-01,
       -4.36349189e-01, -3.65734932e+00,  1.42424725e-02,  4.41686311e-01,
       -5.06416500e-01, -4.91110218e-01, -3.67606258e-01, -9.16697623e-01,
       -7.66032545e-01,  3.43765214e-01, -1.73571028e-01,  1.01709408e-01,
        1.24142559e+00, -9.15581829e-01,  5.94103900e-01, -9.01005902e-01,
        1.42455373e+00,  7.14957629e-01,  2.07220752e+00,  1.10366099e+00,
        4.25809349e-02,  1.75894399e-01, -1.07232604e+00, -6.04427279e-02,
       -1.00377640e+00,  8.70613409e-01,  6.80941192e-01,  5.64858807e-01,
       -1.74863024e+00,  4.94795810e-01, -5.44709650e-01, -5.09540521e-01,
       -7.52871326e-01,  1.11377696e-01,  3.13964093e-01,  1.45299370e-01,
        1.45032647e-01, -2.65548717e-01, -1.13067904e-01,  1.73051782e-01,
       -4.65537241e-01,  1.73994185e+00,  2.91777602e-01,  3.15517995e-01,
       -7.36402436e-02,  3.62596101e-01,  1.15735700e+00,  4.78244197e-01,
        1.53931291e+00,  1.54535564e+00,  4.38641449e-01,  1.28973310e+00,
       -9.24352955e-01, -6.91949583e-01, -3.41433135e-01, -1.86530881e+00,
       -5.91546957e-01,  6.69776715e-01, -2.88034677e+00,  4.88595306e-01,
       -4.49996294e-01,  1.10314191e-01,  1.50269092e+00, -1.01918456e+00,
       -2.91768350e-01,  1.23323462e+00, -3.04121673e-01,  7.03171484e-01,
       -5.36136573e-01, -1.65686100e+00,  1.36641886e+00, -4.62339170e-01,
       -4.08472827e-01, -2.15870445e-01, -1.29718178e+00, -8.60276361e-01,
        1.36609683e+00, -2.19168708e-01,  1.14553847e+00,  6.54693937e-01,
       -4.04113252e-01,  1.17951604e+00, -3.46099714e-01,  1.02466084e+00,
       -1.58027410e-02, -4.21750118e-01,  3.92256853e-01, -3.74025258e-01,
       -1.10442603e-01, -1.01251372e-01,  8.84208799e-01, -1.89425782e+00,
        6.25701222e-01,  1.81848507e+00,  3.01934136e-01,  8.58448095e-01,
       -8.47290424e-02,  8.49728240e-02, -8.40425653e-01,  3.31945938e-01,
       -3.04702879e-03, -1.24448066e+00,  9.62636163e-01,  1.15079962e-01,
       -3.63246941e-01, -3.78291567e-01,  5.51639658e-01, -2.61531707e+00,
       -8.54012244e-01, -1.09186935e+00,  2.11559073e-01,  2.92032613e+00,
       -1.01457890e+00,  7.92654155e-02, -1.31757171e+00, -9.31520339e-01,
        5.51477951e-01, -2.00551468e+00, -7.10165982e-01, -2.70909143e-01,
       -1.39284703e+00, -4.98293536e-01,  4.38800137e-02, -2.63194399e+00,
        9.03775586e-01, -8.18081736e-02,  9.40929350e-01,  9.48301236e-01,
        1.32282756e+00, -2.84931446e-01,  6.02004622e-01, -8.21474047e-01,
       -1.06362395e+00,  2.04949015e+00, -2.00911923e-01,  1.62506265e+00,
       -9.74976089e-02, -1.46506540e-01, -3.82391232e-02,  9.97137080e-01,
       -1.72892062e-01, -7.20581393e-01,  4.65324235e-01,  1.56187632e+00,
        1.70326860e+00,  4.83172615e-01,  9.92962823e-01, -2.18384518e+00,
       -5.01919548e-01, -1.05828263e+00, -7.70721731e-01, -3.22179605e+00,
       -1.84595023e+00, -3.02339211e-02, -1.90196139e-01, -2.32394423e-01,
        4.09353755e-01, -6.13485714e-01, -6.62278426e-01, -1.54966762e+00,
       -1.17299752e+00, -1.53311534e+00, -9.30186225e-01,  6.51623475e-01,
        4.94988493e-01, -6.73537029e-01, -1.02701598e-01,  1.91680375e+00,
        1.55811031e+00,  9.58175359e-01,  2.09689795e-01,  1.39313344e+00,
       -5.99617919e-01,  8.33593917e-02,  1.41580543e+00, -5.28544227e-01,
        8.41235584e-01, -1.02671369e+00, -3.36087306e-01,  8.21699206e-01,
       -1.82404062e-01, -1.14582659e+00,  2.21419901e+00,  6.58478590e-01,
       -1.06370340e-02, -3.85186607e-01,  1.24239109e+00,  1.51811522e+00,
        1.44495169e+00, -6.16005519e-01, -5.72325840e-01, -9.37534417e-02,
        1.26809900e+00,  3.96767805e-03, -6.23277091e-01,  1.63146375e+00,
        1.72491525e-02,  7.36280105e-01, -6.22921045e-01, -3.94954713e-01,
        8.18311260e-01,  1.47300016e+00,  5.64216049e-02, -1.24129313e+00,
        1.21414477e+00,  1.13494791e-01, -2.55427490e-01,  4.24962781e-02,
       -2.19008425e+00,  3.64454722e-01,  4.08980324e-01, -5.88678483e-01,
       -3.08929318e-01, -4.41425451e-01,  2.55719918e-01, -2.51781191e-01,
       -2.62593110e-01,  3.39451936e-01,  8.62832355e-01,  8.31072976e-01,
        7.15610916e-01,  4.10493531e-01, -4.81471982e-02,  1.72816991e+00,
        4.39766229e-01,  8.10173424e-01,  4.55093285e-01,  1.87403014e+00,
        2.06183551e+00, -1.18757920e+00, -1.05768780e+00,  2.71679954e-01,
       -9.90261977e-01,  1.05736907e+00,  1.78931171e+00, -2.48763488e+00,
       -5.49169216e-01,  1.25078532e-01,  4.83542704e-01, -9.16554441e-01,
       -3.77640364e-01, -9.50463161e-02, -4.87714607e-01, -9.94632837e-01,
        2.93277275e-03,  2.27996239e-01, -7.96654009e-01,  2.93739863e-01,
       -2.34796533e-01, -1.31242615e+00, -9.54614634e-01,  1.42716618e-01,
       -1.22064570e+00, -1.07973506e+00,  5.60170655e-01,  2.47899874e+00,
       -3.83100098e-01,  9.24570033e-01, -4.28840868e-01, -6.03387345e-01,
       -6.64539898e-01, -7.87825866e-01, -6.89450503e-01,  1.79798705e+00,
       -1.41143742e+00, -2.53442552e-02,  7.66909381e-01, -6.85778803e-01,
       -3.55717375e-01,  7.11872018e-01, -1.91636520e+00,  1.70795571e+00,
       -1.20626498e+00,  8.51447217e-01,  5.77416356e-01,  1.68988573e+00,
        1.82891767e-01, -1.21804620e+00, -7.36378713e-02,  6.36593947e-01,
        1.08437920e+00, -4.92342142e-01, -4.74796987e-01,  1.34641348e+00,
        6.95854732e-01,  6.42559945e-01, -7.48504751e-01, -2.25123716e-01,
       -3.76934949e-01, -1.29760138e+00,  6.87281383e-02,  1.44751857e+00,
       -1.78857160e+00, -5.26110213e-01, -7.49249541e-01,  2.65830043e-01,
        2.85252936e-01,  2.54789072e-01, -7.34359191e-01,  7.37924189e-01,
        2.45441389e-01, -1.18925023e+00,  9.59515062e-01,  1.32803318e+00,
        5.17924064e-01,  1.54123356e-01,  1.07182468e+00, -1.65351213e+00,
       -5.30562622e-02,  7.82555217e-01,  1.07924893e+00, -2.08556148e-01,
       -1.37157745e+00,  1.00092653e+00,  1.11184413e+00,  4.18797074e-01,
        6.14704860e-01, -5.72964122e-01,  1.02036471e+00,  7.37757927e-02,
        2.25109376e-01,  2.37196602e+00, -3.34582514e+00,  6.57597837e-01,
       -4.57837007e-01,  4.08849679e-01,  8.36292387e-01,  8.36077414e-01,
        1.14512515e+00,  8.16453574e-01,  1.25193044e+00, -1.62621028e+00,
        5.06255131e-01, -3.29719711e-01,  8.98845833e-01,  1.95158239e+00,
       -3.08333406e-01,  4.28554997e-02,  1.19064114e+00, -1.43967085e-01,
        1.43109151e+00,  4.98768081e-01, -2.77036404e-01,  4.91948129e-01,
       -1.47463430e+00,  1.20071744e+00,  4.51618606e-01, -1.24156608e-01,
        4.57711877e-01, -7.49943669e-01,  6.96555813e-01, -3.23743342e-01,
       -3.67319455e-01,  7.65761716e-01, -8.64939669e-01,  4.52723444e-01,
        2.36943333e-02, -7.61556579e-01,  1.50364984e+00,  1.29071422e+00,
        4.23416646e-03,  6.01119966e-01,  3.82600341e-01,  4.62659783e-02,
        8.94882003e-01,  8.20072739e-01,  7.31828867e-02, -1.84338208e-01,
       -3.68562236e-01, -3.23852473e-01,  5.19383058e-02,  1.43682204e+00,
       -1.03369419e-03, -9.72147009e-01,  8.10177443e-01, -1.10247152e+00,
       -1.03975006e+00,  1.13581679e+00, -4.43405622e-01, -1.21492891e+00,
       -6.76247418e-02, -9.72896124e-01,  1.40843521e+00, -6.70495451e-01,
        2.25992661e-01, -8.61851551e-01,  3.65851397e-01, -6.94825650e-01,
        1.22748660e+00, -1.37849513e+00,  3.30541959e-01,  3.42351804e-01,
        2.31617310e-01,  4.74768119e-01,  2.02951238e+00, -4.00923434e-02,
        6.38553620e-01,  1.08441972e+00,  2.64467380e-02,  7.12293778e-02,
       -2.90439332e-01,  1.86642532e-01, -9.54139454e-01, -4.45905355e-01,
       -5.19265458e-02,  9.42586005e-01, -1.37761989e+00,  6.82292839e-01,
        1.84606507e+00,  1.07904448e+00,  6.49270940e-01, -9.72028924e-02,
        1.02684314e-01,  1.00031437e+00,  2.45689942e-01, -1.08932922e+00,
        1.09334582e+00, -9.27626207e-01, -4.51014475e-01, -1.20902321e-01,
        8.49203380e-01, -6.47981468e-01, -2.37189233e+00, -5.58406574e-01,
       -6.01204156e-01, -6.11193757e-01,  3.48163614e-01, -1.64401538e+00,
        1.60604733e+00, -2.95596561e-01,  2.06845880e-01, -2.00642523e+00,
        1.32182737e+00, -1.57082180e+00, -1.13748040e+00,  1.45362501e+00,
        9.34241701e-01,  1.02185560e+00,  1.24584648e+00, -1.40586755e-01,
       -6.80611469e-01,  1.06660063e-01,  8.86449701e-01, -1.25925633e+00,
       -9.53199039e-01, -6.72659394e-01, -1.38105071e+00, -1.96827685e-01,
        9.20656171e-01,  1.00801854e+00,  7.88685943e-01, -1.76532119e+00,
       -1.39432257e+00, -5.85394832e-01,  3.41119638e-01, -4.79067875e-01,
       -4.42713239e-01,  3.81154798e-01,  7.53797598e-01, -6.93709628e-01,
        2.61007683e-01,  4.63408341e-01, -1.31519662e-01, -2.28316277e+00,
        1.12954402e+00, -4.34499188e-01,  3.15159479e-01,  2.77272780e-01,
        3.14576091e-01,  7.27456132e-01,  1.47946562e+00, -1.20109535e+00,
        3.12447129e-01, -2.18720942e-01, -1.03629031e+00, -2.50047254e-01,
        7.72414061e-01, -1.98212004e+00,  6.70206737e-02,  7.69699896e-01,
        3.72682570e-01, -2.38771538e-01, -8.35866016e-01, -1.25188518e+00,
        9.27144767e-01,  1.29342258e+00,  1.23660128e+00, -6.05813721e-01,
        5.14714811e-01, -1.30340543e-01, -4.66127480e-01,  1.50733260e+00,
        1.45054027e+00,  1.14941154e+00,  1.68363127e+00, -1.94872410e-01,
       -8.76970641e-01, -1.97622164e+00,  1.84926711e-01, -1.78120243e-01,
        1.19696387e+00,  1.21096565e+00, -3.58125947e-01, -1.33240754e+00,
        3.26718521e-01,  1.30504481e+00, -3.96372785e-01, -4.91999247e-01,
       -2.33604980e-02, -6.71764544e-01,  1.15090353e+00,  8.78291813e-02,
        1.78521652e-01, -1.75962613e+00,  1.26962650e+00,  1.94961840e+00,
       -5.33762527e-01,  9.70938193e-01,  1.10275311e+00,  5.01026685e-01,
        3.83164908e-01,  2.39542509e-02,  2.45437295e-03, -7.98630039e-01,
       -2.34603264e-01, -3.80262019e-02,  1.51019362e+00,  7.91994356e-01,
        8.47185148e-01, -2.98821683e-01,  9.36754375e-01, -3.00829287e-01,
       -1.72023480e+00, -6.64842423e-01,  1.47773299e+00, -1.12487462e-01,
       -1.58213129e+00, -5.77220907e-02, -5.26235623e-01, -9.64281582e-01,
        1.26761560e+00,  6.17554717e-01,  5.93873950e-02, -4.97505339e-01,
       -2.08995175e+00,  2.71511696e-01, -9.74525971e-01, -1.86407800e+00,
        4.74867144e-01,  3.38419143e-01,  1.01334209e+00,  1.66133478e+00,
       -9.97230758e-01, -5.41921324e-01,  1.55819069e+00, -1.02506971e+00,
       -8.30080341e-01, -6.64280541e-01,  2.98058185e-01,  1.50002202e+00,
        1.85899707e+00,  7.79000152e-01,  2.65495003e-02, -1.19321796e+00,
       -1.13719390e+00, -4.80393647e-01, -9.68172708e-01, -1.19164031e+00,
        1.79977343e-01, -3.63026425e-01, -1.15877228e+00, -2.98304992e-01,
        1.68326069e-01, -9.33257654e-01, -1.44699058e+00, -1.23627230e-01,
        1.21489126e+00, -1.31051501e+00,  1.31021467e-01,  7.94629406e-01,
        1.13395350e+00,  6.06918888e-01, -5.40050223e-02, -1.43202548e-01])

In [56]:
cats = pd.qcut(data, 4)  # Cut into quartiles
cats

[(-3.2479999999999998, -0.629], (-0.629, 0.000734], (-3.2479999999999998, -0.629], (-0.629, 0.000734], (-3.2479999999999998, -0.629], ..., (0.000734, 0.702], (0.000734, 0.702], (0.000734, 0.702], (0.702, 3.617], (-3.2479999999999998, -0.629]]
Length: 1000
Categories (4, interval[float64]): [(-3.2479999999999998, -0.629] < (-0.629, 0.000734] < (0.000734, 0.702] < (0.702, 3.617]]

In [57]:
pd.value_counts(cats)

(-3.2479999999999998, -0.629]    250
(-0.629, 0.000734]               250
(0.000734, 0.702]                250
(0.702, 3.617]                   250
dtype: int64

Similar to **cut** you can pass your own quantiles (numbers between 0 and 1, inclusive):

In [60]:
qcats = pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]) 
qcats

[(-1.23, 0.000734], (-1.23, 0.000734], (-1.23, 0.000734], (-1.23, 0.000734], (-3.2479999999999998, -1.23], ..., (0.000734, 1.321], (0.000734, 1.321], (0.000734, 1.321], (1.321, 3.617], (-1.23, 0.000734]]
Length: 1000
Categories (4, interval[float64]): [(-3.2479999999999998, -1.23] < (-1.23, 0.000734] < (0.000734, 1.321] < (1.321, 3.617]]

In [59]:
pd.value_counts(qcats)

(-1.23, 0.000734]               400
(0.000734, 1.321]               400
(-3.2479999999999998, -1.23]    100
(1.321, 3.617]                  100
dtype: int64

## 5.3  String Manipulation 

Python has long been a popular raw data manipulation language in part due to its ease of use for string and text processing. Most text operations are made simple with the string object’s built-in methods. For more complex pattern matching and text manipulations, regular expressions may be needed. pandas adds to the mix by enabling you to apply string and regular expressions concisely on whole arrays of data, additionally handling the annoyance of missing data. 


### 5.3.1 String Object Methods 

In many string munging and scripting applications, built-in string methods are sufficient. As an example, a comma-separated string can be broken into pieces with **split**:

In [7]:
val = 'a,b,            guido'
val.split(',')

['a', 'b', '            guido']

**split** is often combined with **strip** to trim whitespace (including line breaks):

In [11]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

These substrings could be concatenated together with a two-colon delimiter using addition:

In [14]:
first, second, third = pieces
first + '::' + second + '::' + third 
#pieces

'a::b::guido'

But this isn’t a practical generic method. A faster and more Pythonic way is to pass a list or tuple to the **join** method on the string '::':

In [53]:
':'.join(pieces)

'a:b:guido'

In [31]:
val

'a,b,            guido'

Other methods are concerned with locating substrings. Using Python’s **in** keyword is the best way to detect a substring, though **index** and **find* can also be used:

In [33]:
'guido' in val

True

In [35]:
val.index(',')

1

In [39]:
val.find('-1')

1

Note the difference between **find** and **index** is that index raises an exception if the string isn’t found (versus returning –1):

In [47]:
val.index(':')

ValueError: substring not found

Relatedly, **count** returns the number of occurrences of a particular substring:

In [71]:
val.count(',')

2

**replace** will substitute occurrences of one pattern for another. It is commonly used to delete patterns, too, by passing an empty string:

In [72]:
val.replace(',', '::')

'a::b::  guido'

In [73]:
val.replace(',', '')

'ab  guido'

See Table 5-3 for a listing of some of Python’s string methods. Regular expressions can also be used with many of these operations, as you’ll see.

<br>
<center>Table 5.3: Python built-in string methods</center>
<img src="Table5.3.jpg">

### 5.3.2  Regular Expressions 

*Regular expressions* provide a flexible way to search or match (often more complex) string patterns in text. A single expression, commonly called a *regex*, is a string formed according to the regular expression language. Python’s built-in **re** module is responsible for applying regular expressions to strings.

The **re** module functions fall into three categories: pattern matching, substitution, and splitting. Naturally these are all related; a *regex* describes a pattern to locate in the text, which can then be used for many purposes. Let’s look at a simple example:

Suppose we wanted to split a string with a variable number of whitespace characters (tabs, spaces, and newlines). The *regex* describing one or more whitespace characters is **\s+**:

In [59]:
import re
text = "foo    bar \t baz  \tqux"
text

'foo    bar \t baz  \tqux'

In [61]:
re.split('\s+', text)

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\jingy\AppData\Local\Temp\ipykernel_64964\2849330038.py:1: SyntaxWarning: invalid escape sequence '\s'
  re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

When you call **re.split('\s+', text)**, the regular expression is first compiled, and then its split method is called on the passed text. You can compile the *regex* yourself with **re.compile**, forming a reusable *regex* object:

In [65]:
regex = re.compile('\s+')

regex.split(text)

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\jingy\AppData\Local\Temp\ipykernel_64964\11033884.py:1: SyntaxWarning: invalid escape sequence '\s'
  regex = re.compile('\s+')

['foo', 'bar', 'baz', 'qux']

If, instead, you wanted to get a list of all patterns matching the *regex*, you can use the **findall** method:

In [67]:
regex.findall(text)

['    ', ' \t ', '  \t']

**match** and **search** are closely related to **findall**. While **findall** returns all matches in a string, **search** returns only the first match. More rigidly, **match** only matches at the beginning of the string. As a less trivial example, let’s consider a block of text and a regular expression capable of identifying most email addresses:

In [120]:
text = """ Dave dave@google.com 
Steve steve@gmail.com 
Rob rob@gmail.com 
Ryan ryan@yahoo.com 
""" 
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
#A-Z: uppercase letters

#0-9: digits

#._%+-: allowed special characters

#+: one or more of these characters

#@: matches the @ symbol literally

#re.IGNORECASE makes the regex case-insensitive 
regex = re.compile(pattern, flags=re.IGNORECASE)

Using **findall** on the text produces a list of the email addresses:

In [123]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

**search** returns a special match object for the first email address in the text. For the preceding *regex*, the match object can only tell us the start and end position of the pattern in the string:

In [50]:
m = regex.search(text)
m

In [52]:
text[m.start():m.end()]

'dave@google.com'

**regex.match** returns None, as it only will match if the pattern occurs at the start of the string:

In [55]:
print(regex.match(text))

None

Relatedly, **sub** will return a new string with occurrences of the pattern replaced by the a new string:

In [58]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED

Suppose you wanted to find email addresses and simultaneously segment each address into its three components: username, domain name, and domain suffix. To do this, put parentheses around the parts of the pattern to segment:

In [74]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)

A match object produced by this modified *regex* returns a tuple of the pattern components with its **groups** method:

In [64]:
m = regex.match('wesm@bright.net')
m.groups()

('wesm', 'bright', 'net')

**findall** returns a list of tuples when the pattern has groups:

In [67]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

**sub** also has access to groups in each match using special symbols like \1 and \2. The symbol \1 corresponds to the first matched group, \2 corresponds to the second, and so forth:

In [70]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com

There is much more to regular expressions in Python, most of which is outside our scope. Table 5-4 provides a brief summary.

<br>
<center>Table 5.4: Regular expression methods</center>
<img src="Table5.4.jpg">

### 5.3.3 Vectorized String Functions in pandas 

Cleaning up a messy dataset for analysis often requires a lot of string munging and regularization. To complicate matters, a column containing strings will sometimes have missing data:

In [78]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com', 'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [80]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

String and regular expression methods can be applied (passing a **lambda** or other function) to each value using **data.map**, but it will fail on the NA (null) values. To cope with this, Series has array-oriented methods for string operations that skip NA values. These are accessed through Series’s **str** attribute; for example, we could check whether each email address has 'gmail' in it with **str.contains**:

In [83]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

Regular expressions can be used, too, along with any **re** options like **IGNORECASE**:

In [86]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [90]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

There are a couple of ways to do vectorized element retrieval. Either use **str.get** or index into the **str** attribute:

In [95]:
matches = data.str.match(pattern, flags=re.IGNORECASE)
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

To access elements in the embedded lists, we can pass an index to either of these functions:

In [98]:
matches.str.get(1)

AttributeError: Can only use .str accessor with string values!

In [101]:
matches.str[0]

AttributeError: Can only use .str accessor with string values!

You can similarly slice strings using this syntax:

In [103]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

See Table 5-5 for more pandas string methods.

<br>
<center>Table 5.5: Partial listing of vectorized string methods</center>
<img src="Table5.5.jpg">